### ISSUE TITLE
Switching to dragonpilot doesn't work

### ISSUE THREAD

**Issue by vetmiker** [emu-sh/.oh-my-comma#43]
When I try to switch to Dragonpilot I get a "Invalid username! https://github.com/dragonpilot-community/openpilot does not exist"

Here's the command I'm running: `emu fork switch dragonpilot-community -b testing`

It's worth noting that the repository is actually https://github.com/dragonpilot-community/dragonpilot (not openpilot). Is there a way to specify the reposity URL? I tried `emu fork switch dragonpilot-community/dragonpilot -b testing` but got invalid username.

**Comment by ShaneSmiskol** [comment]
Hi, thanks for finding this issue, I actually never tested to make sure that dragonpilot linked to the correct repo by `dragonpilot-community` rather than `dragonpilot`. Usually if a single user forks openpilot getting the `/openpilot` repo from GitHub would redirrect us if the user changed the fork repo name, but since dragonpilot is a GitHub community account, or group, it didn't redirect from the user correctly. I'll add an alias for this soon!

**Comment by vetmiker** [comment]
Thanks Shane!!

**Comment by AskAlice** [comment]
The implication is that if it's not a comma supported fork they have to be using a different repository name as openpilot is trademarked. That being said, you can always `git remote add remoteNameHere https://github.com/username/reponame.git` and then checkout the branch you want.

**Comment by ShaneSmiskol** [comment]
I'll work on adding this alias today
